<div id="header">
    <a id="header__logo" href="#"></a>
    
    <div id="header__menu_left">
        <a class="item" href="#">Home</a>
        <div class="item">
            <div class="sn dropdown">
                <div class="text">Explore</div>
                <div class="menu">
                    <a href="#" class="item">Item 1</a>
                </div>
            </div>
        </div>
        </li>
    </div>
</div>